# Use Docker image with Java 8 (Update 101) and Maven (3.3.9) running on Ubuntu 16.04
image: kaiwinter/docker-java8-maven

variables:  
  MAVEN_CLI_OPTS: "-B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  
# Cache the compiled project & libraries between jobs
cache:
  paths:
    - .m2/
    - target/

# Stages
stages:
  - Build
  - Test
  - Static-analysis
  - Coverage
  

# Build stage
build:
  stage: Build
  script:
    - "mvn $MAVEN_CLI_OPTS compile"


# Test stage
junit-tests:
  stage: Test
  script:
    - "mvn $MAVEN_CLI_OPTS test"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

 
# Static analysis stage 
checkstyle:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS checkstyle:check"

spotbugs:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS spotbugs:check"

pmd:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS pmd:check"

cpd:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS pmd:cpd-check"


# Coverage stage      
clover:
    stage: Coverage
    script:
        - "mvn $MAVEN_CLI_OPTS clover:instrument clover:log"