# Use Docker image with Java 8 (Update 101) and Maven (3.3.9) running on Ubuntu 16.04
image: kaiwinter/docker-java8-maven

# Cache the compiled project & libraries between jobs
cache:
  paths:
    - .m2/repository/
    - target/

    
# Stages
stages:
  - Build
  - Test
  - Static-analysis
  - Coverage
  

# Build stage
build:
  stage: Build
  script:
    - "mvn -B compile"


# Test stage
junit-tests:
  stage: Test
  script:
    - "mvn -B test"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

 
# Static analysis stage 
checkstyle:
    stage: Static-analysis
    script:
      - "mvn -B checkstyle:check"

spotbugs:
    stage: Static-analysis
    script:
      - "mvn -B spotbugs:check"

pmd:
    stage: Static-analysis
    script:
      - "mvn -B pmd:check"

cpd:
    stage: Static-analysis
    script:
      - "mvn -B pmd:cpd-check"


# Coverage stage      
clover:
    stage: Coverage
    script:
        - "mvn -B clover:instrument clover:log"