# Reference: https://docs.gitlab.com/ee/ci/yaml/
# Examples for different languages can be found in doc/CI. Other examples can be found at: https://gitlab.com/gitlab-org/gitlb-ce/tree/master/lib/gitlb/ci/templates

# Docker image
# Change to your platform
image: busybox:latest

# Variables
# Allows you to define custom variables
variables:

# Cache libraries in between jobs
# https://docs.gitlab.com/ee/ci/caching/index.html
cache:
  paths:

# Displays time before each script
before_script:
  - date

# Displays time after each script
after_script:
  - date

# Stages
stages:
  - build
  - test

# Jobs
build:
  stage: build

  # Build steps
  script:
    - echo 'Add something here'

  artifacts:
    # Define which files/directories should be kept as artifacts e.g. jars
    paths:

test:
  stage: test

  # Test steps
  script:
    - echo 'Add something here'
    - echo 'metric_name metric_value' >> metrics.txt

  artifacts:
    # Define which files/directories should be kept as artifacts e.g. jars
    paths:

    reports:
      # Show differences in unit tests results in Gitlab GUI
      # https://docs.gitlab.com/ee/ci/junit_test_reports.html
      junit:

      # Shows metrics in your GitLab Merge Request GUI
      # https://docs.gitlab.com/ee/ci/metrics_reports.html
      metrics: metrics.txt
  
# Optional security and license checks
include:
  # Static Application Security Testing (SAST)
  # works with most languages
  # https://docs.gitlab.com/ee/user/application_security/sast/index.html
  template: SAST.gitlab-ci.yml

  # Dynamic Application Security Testing (DAST)
  # tests security of web facing applications
  # Needs DAST_WEBSITE variable e.g. DAST_WEBSITE: https://example.com
  # https://docs.gitlab.com/ee/user/application_security/dast/index.html
  #template: DAST.gitlab-ci.yml

  # Dependency Scanning
  # works with most languages
  # https://docs.gitlab.com/ee/user/application_security/dependency_scanning/index.html
  template: Dependency-Scanning.gitlab-ci.yml

  # License Management
  # works with most languages
  # https://docs.gitlab.com/ee/user/application_security/license_management/index.html
  template: License-Management.gitlab-ci.yml

