# Docker image obtained from https://hub.docker.com/_/maven/
image: maven:3.6.1-jdk-8-slim

# Maven CLI flags
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "-B"
  
# Cache downloaded dependencies and plugins
cache:
  paths:
    - .m2/repository
  policy: pull


# Stages
stages:
  - Build
  - Test
  - Static-analysis
  - Coverage


# Build stage
build:
  stage: Build
  script:
    - "mvn $MAVEN_CLI_OPTS compile"
  cache:
    policy: pull-push
  artifacts:
    paths:
      - target/


# Test stage
junit-tests:
  stage: Test
  script:
    - "mvn $MAVEN_CLI_OPTS test"
  dependencies:
    - build
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

 
# Static analysis stage 
checkstyle:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS checkstyle:check"
    dependencies: []

spotbugs:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS spotbugs:check"
    dependencies: []

pmd:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS pmd:check"
    dependencies: []

cpd:
    stage: Static-analysis
    script:
      - "mvn $MAVEN_CLI_OPTS pmd:cpd-check"
    dependencies: []


# Coverage stage      
clover:
    stage: Coverage
    script:
        - "mvn $MAVEN_CLI_OPTS clover:instrument clover:log"
    dependencies: []