language: java
jdk:
  - oraclejdk8

install: true

jobs:
  include:
  - stage: test
    script: mvn -B test

  - stage: static-analysis
    script: mvn -B checkstyle:check
    name: "Checkstyle"
  - script: mvn -B pmd:check
    name: "PMD"
  - script: mvn -B pmd:cpd-check
    name: "CPD"
  - script: mvn -B spotbugs:check
    name: "SpotBugs"

  - stage: coverage
    script: mvn -B clover:instrument clover:log
    after-success:
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

stages:
  - test
  - static-analysis
  - coverage

cache:
  directories:
  - $HOME/.m2
