language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

jobs:
  include:
  - stage: test
    script: mvn -B test
    name: "JUnit"

  - stage: static-analysis
    script: mvn -B checkstyle:check
    name: "Checkstyle"
  - script: mvn -B pmd:check
    name: "PMD"
  - script: mvn -B pmd:cpd-check
    name: "CPD"
  - script: mvn -B spotbugs:check
    name: "SpotBugs"

  - stage: coverage
    script: mvn -B clover:instrument clover:log
    name "Clover"

stages:
  - test
  - static-analysis
  - coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
